// 농장 DB — codes.gs FARM_DB 이관, 다비연구소는 직영 맨 아래
export const FARMS = {
  DB1001: { name: '성진', group: '직영', vet: '양승혁' },
  DB1002: { name: '대덕', group: '직영', vet: '박지형' },
  DB1003: { name: '디앤디', group: '직영', vet: '고상억' },
  DB2005: { name: '도화', group: '직영', vet: '고상억' },
  DB2006: { name: '대월', group: '직영', vet: '고상억' },
  DB2007: { name: '삼성', group: '직영', vet: '이희원' },
  DB2008: { name: '여울목', group: '직영', vet: '고상억' },
  DB2009: { name: '해림', group: '직영', vet: '이희원' },
  DB2010: { name: '문강', group: '직영', vet: '박지형' },
  DB2011: { name: '서후', group: '직영', vet: '박지형' },
  DB2012: { name: '원산', group: '직영', vet: '이희원' },
  DB2013: { name: '고흥', group: '직영', vet: '장석현' },
  DB2014: { name: '진천', group: '직영', vet: '박지형' },
  DB2015: { name: '다원', group: '직영', vet: '고상억' },
  DB4014: { name: '버들', group: '직영', vet: '양승혁' },
  DB4006: { name: '거목', group: '직영', vet: '-' },
  DB3001: { name: '조산', group: '협력', vet: '박지형' },
  DB3002: { name: '삼경', group: '협력', vet: '장석현' },
  DB3005: { name: '관인', group: '협력', vet: '양승혁' },
  DB3007: { name: '효돈', group: '협력', vet: '양승혁' },
  DB3014: { name: '운도', group: '협력', vet: '양승혁' },
  DB3015: { name: '성일', group: '협력', vet: '양승혁' },
  DB3016: { name: '남도', group: '협력', vet: '장석현' },
  DB3017: { name: '성산', group: '협력', vet: '이희원' },
  DB3019: { name: '에이스팜', group: '협력', vet: '이희원' },
  DB3020: { name: '지혜', group: '협력', vet: '박지형' },
  DB3021: { name: '화진', group: '협력', vet: '양승혁' },
  DB3022: { name: '한빛피플', group: '협력', vet: '장석현' },
  DB3023: { name: '한빛청주', group: '협력', vet: '박지형' },
  DB3024: { name: '동산', group: '협력', vet: '장석현' },
  DB3025: { name: '인솔', group: '협력', vet: '박지형' },
  DB5001: { name: '중원', group: 'SP센터', vet: '장석현' },
  DB5002: { name: '조치원', group: 'SP센터', vet: '이희원' },
  DB5003: { name: '양산', group: 'SP센터', vet: '양승혁' },
  DB6001: { name: '북부유전', group: 'SP센터', vet: '장석현' },
  DB4001: { name: '자영', group: '위탁장', vet: '장석현' },
  DB4002: { name: '구산', group: '위탁장', vet: '박지형' },
  DB4003: { name: '유기', group: '위탁장', vet: '박지형' },
  DB4009: { name: '포월', group: '위탁장', vet: '양승혁' },
  DB4011: { name: '능국', group: '위탁장', vet: '장석현' },
  DB9001: { name: '다비연구소', group: '직영', vet: '-' },
  DB9002: { name: '다비유종비교', group: '직영', vet: '-' },
  DB9003: { name: '발라드동물병원', group: '직영', vet: '-' },
  DB9004: { name: '종돈수송차량', group: '직영', vet: '-' },
} as const;

export type FarmCode = keyof typeof FARMS;

export const FARM_GROUPS = ['직영', '협력', 'SP센터', '위탁장'] as const;
